"""add user_id to quotes

Revision ID: 17a5a759ece3
Revises: c18e0f1d81e1
Create Date: 2026-06-14 16:21:19.012243

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17a5a759ece3"
down_revision: str | Sequence[str] | None = "c18e0f1d81e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quotes", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "quotes", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "quotes", type_="foreignkey")
    op.drop_column("quotes", "user_id")
    # ### end Alembic commands ###
