"""create raffle tables

Revision ID: c18e0f1d81e1
Revises: d2be1117b301
Create Date: 2026-06-07 23:21:49.832141

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c18e0f1d81e1"
down_revision: str | Sequence[str] | None = "d2be1117b301"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quotes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_name", sa.String(length=100), nullable=False),
        sa.Column("contact_method", sa.String(length=20), nullable=False),
        sa.Column("contact_value", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("postal_code", sa.String(length=10), nullable=False),
        sa.Column("square_meters", sa.Float(), nullable=False),
        sa.Column("paint_product", sa.String(length=80), nullable=False),
        sa.Column("estimated_price", sa.Float(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("user_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quotes_id"), "quotes", ["id"], unique=False)
    op.create_table(
        "raffles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("prize_title", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_numbers", sa.Integer(), nullable=False),
        sa.Column("numbers_per_branch", sa.Integer(), nullable=False),
        sa.Column("max_codes_per_batch", sa.Integer(), nullable=False),
        sa.Column("max_batches_per_user_24h", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_raffles_id"), "raffles", ["id"], unique=False)
    op.create_index(op.f("ix_raffles_slug"), "raffles", ["slug"], unique=True)
    op.create_table(
        "raffle_branches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raffle_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("number_start", sa.Integer(), nullable=False),
        sa.Column("number_end", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["raffle_id"], ["raffles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("raffle_id", "slug", name="uq_raffle_branches_raffle_slug"),
    )
    op.create_index(
        op.f("ix_raffle_branches_id"), "raffle_branches", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_raffle_branches_raffle_id"),
        "raffle_branches",
        ["raffle_id"],
        unique=False,
    )
    op.create_table(
        "raffle_ticket_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raffle_id", sa.Integer(), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("code_last4", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("used_by_user_id", sa.Integer(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["raffle_id"], ["raffles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["used_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raffle_ticket_codes_code_hash"),
        "raffle_ticket_codes",
        ["code_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_raffle_ticket_codes_id"), "raffle_ticket_codes", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_raffle_ticket_codes_raffle_id"),
        "raffle_ticket_codes",
        ["raffle_id"],
        unique=False,
    )
    op.create_index(
        "ix_raffle_ticket_codes_raffle_status",
        "raffle_ticket_codes",
        ["raffle_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_ticket_codes_used_by_user_id"),
        "raffle_ticket_codes",
        ["used_by_user_id"],
        unique=False,
    )
    op.create_table(
        "raffle_numbers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raffle_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("taken_by_user_id", sa.Integer(), nullable=True),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["raffle_branches.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["raffle_id"], ["raffles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["taken_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "raffle_id", "number", name="uq_raffle_numbers_raffle_number"
        ),
    )
    op.create_index(
        op.f("ix_raffle_numbers_branch_id"),
        "raffle_numbers",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_numbers_id"), "raffle_numbers", ["id"], unique=False
    )
    op.create_index(
        "ix_raffle_numbers_raffle_branch_status",
        "raffle_numbers",
        ["raffle_id", "branch_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_numbers_raffle_id"),
        "raffle_numbers",
        ["raffle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_numbers_taken_by_user_id"),
        "raffle_numbers",
        ["taken_by_user_id"],
        unique=False,
    )
    op.create_table(
        "raffle_ticket_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raffle_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("submitted_count", sa.Integer(), nullable=False),
        sa.Column("accepted_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["raffle_branches.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["raffle_id"], ["raffles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raffle_ticket_batches_branch_id"),
        "raffle_ticket_batches",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_ticket_batches_id"),
        "raffle_ticket_batches",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_raffle_ticket_batches_ip_created",
        "raffle_ticket_batches",
        ["ip_address", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_ticket_batches_raffle_id"),
        "raffle_ticket_batches",
        ["raffle_id"],
        unique=False,
    )
    op.create_index(
        "ix_raffle_ticket_batches_user_created",
        "raffle_ticket_batches",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_ticket_batches_user_id"),
        "raffle_ticket_batches",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "raffle_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raffle_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=False),
        sa.Column("ticket_code_id", sa.Integer(), nullable=False),
        sa.Column("raffle_number_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("selected_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["raffle_ticket_batches.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["raffle_branches.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["raffle_id"], ["raffles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["raffle_number_id"], ["raffle_numbers.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["ticket_code_id"], ["raffle_ticket_codes.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "raffle_id", "raffle_number_id", name="uq_raffle_entries_number_id"
        ),
        sa.UniqueConstraint(
            "raffle_id", "selected_number", name="uq_raffle_entries_selected_number"
        ),
        sa.UniqueConstraint(
            "raffle_id", "ticket_code_id", name="uq_raffle_entries_ticket_code"
        ),
    )
    op.create_index(
        op.f("ix_raffle_entries_batch_id"), "raffle_entries", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_raffle_entries_branch_id"),
        "raffle_entries",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_entries_id"), "raffle_entries", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_raffle_entries_raffle_id"),
        "raffle_entries",
        ["raffle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_entries_raffle_number_id"),
        "raffle_entries",
        ["raffle_number_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_entries_ticket_code_id"),
        "raffle_entries",
        ["ticket_code_id"],
        unique=False,
    )
    op.create_index(
        "ix_raffle_entries_user_created",
        "raffle_entries",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_entries_user_id"), "raffle_entries", ["user_id"], unique=False
    )
    op.create_table(
        "raffle_ticket_batch_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("ticket_code_id", sa.Integer(), nullable=True),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("code_last4", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["raffle_ticket_batches.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["ticket_code_id"], ["raffle_ticket_codes.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raffle_ticket_batch_items_batch_id"),
        "raffle_ticket_batch_items",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_ticket_batch_items_id"),
        "raffle_ticket_batch_items",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raffle_ticket_batch_items_ticket_code_id"),
        "raffle_ticket_batch_items",
        ["ticket_code_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_quptes_id"), table_name="quptes")
    op.drop_table("quptes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quptes",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("customer_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("contact_method", sa.VARCHAR(length=20), nullable=False),
        sa.Column("contact_value", sa.VARCHAR(length=120), nullable=False),
        sa.Column("state", sa.VARCHAR(length=50), nullable=False),
        sa.Column("city", sa.VARCHAR(length=100), nullable=False),
        sa.Column("postal_code", sa.VARCHAR(length=10), nullable=False),
        sa.Column("square_meters", sa.FLOAT(), nullable=False),
        sa.Column("paint_product", sa.VARCHAR(length=80), nullable=False),
        sa.Column("estimated_price", sa.FLOAT(), nullable=False),
        sa.Column("payload_json", sqlite.JSON(), nullable=False),
        sa.Column("result_json", sqlite.JSON(), nullable=False),
        sa.Column("user_type", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quptes_id"), "quptes", ["id"], unique=False)
    op.drop_index(
        op.f("ix_raffle_ticket_batch_items_ticket_code_id"),
        table_name="raffle_ticket_batch_items",
    )
    op.drop_index(
        op.f("ix_raffle_ticket_batch_items_id"), table_name="raffle_ticket_batch_items"
    )
    op.drop_index(
        op.f("ix_raffle_ticket_batch_items_batch_id"),
        table_name="raffle_ticket_batch_items",
    )
    op.drop_table("raffle_ticket_batch_items")
    op.drop_index(op.f("ix_raffle_entries_user_id"), table_name="raffle_entries")
    op.drop_index("ix_raffle_entries_user_created", table_name="raffle_entries")
    op.drop_index(op.f("ix_raffle_entries_ticket_code_id"), table_name="raffle_entries")
    op.drop_index(
        op.f("ix_raffle_entries_raffle_number_id"), table_name="raffle_entries"
    )
    op.drop_index(op.f("ix_raffle_entries_raffle_id"), table_name="raffle_entries")
    op.drop_index(op.f("ix_raffle_entries_id"), table_name="raffle_entries")
    op.drop_index(op.f("ix_raffle_entries_branch_id"), table_name="raffle_entries")
    op.drop_index(op.f("ix_raffle_entries_batch_id"), table_name="raffle_entries")
    op.drop_table("raffle_entries")
    op.drop_index(
        op.f("ix_raffle_ticket_batches_user_id"), table_name="raffle_ticket_batches"
    )
    op.drop_index(
        "ix_raffle_ticket_batches_user_created", table_name="raffle_ticket_batches"
    )
    op.drop_index(
        op.f("ix_raffle_ticket_batches_raffle_id"), table_name="raffle_ticket_batches"
    )
    op.drop_index(
        "ix_raffle_ticket_batches_ip_created", table_name="raffle_ticket_batches"
    )
    op.drop_index(
        op.f("ix_raffle_ticket_batches_id"), table_name="raffle_ticket_batches"
    )
    op.drop_index(
        op.f("ix_raffle_ticket_batches_branch_id"), table_name="raffle_ticket_batches"
    )
    op.drop_table("raffle_ticket_batches")
    op.drop_index(
        op.f("ix_raffle_numbers_taken_by_user_id"), table_name="raffle_numbers"
    )
    op.drop_index(op.f("ix_raffle_numbers_raffle_id"), table_name="raffle_numbers")
    op.drop_index("ix_raffle_numbers_raffle_branch_status", table_name="raffle_numbers")
    op.drop_index(op.f("ix_raffle_numbers_id"), table_name="raffle_numbers")
    op.drop_index(op.f("ix_raffle_numbers_branch_id"), table_name="raffle_numbers")
    op.drop_table("raffle_numbers")
    op.drop_index(
        op.f("ix_raffle_ticket_codes_used_by_user_id"), table_name="raffle_ticket_codes"
    )
    op.drop_index(
        "ix_raffle_ticket_codes_raffle_status", table_name="raffle_ticket_codes"
    )
    op.drop_index(
        op.f("ix_raffle_ticket_codes_raffle_id"), table_name="raffle_ticket_codes"
    )
    op.drop_index(op.f("ix_raffle_ticket_codes_id"), table_name="raffle_ticket_codes")
    op.drop_index(
        op.f("ix_raffle_ticket_codes_code_hash"), table_name="raffle_ticket_codes"
    )
    op.drop_table("raffle_ticket_codes")
    op.drop_index(op.f("ix_raffle_branches_raffle_id"), table_name="raffle_branches")
    op.drop_index(op.f("ix_raffle_branches_id"), table_name="raffle_branches")
    op.drop_table("raffle_branches")
    op.drop_index(op.f("ix_raffles_slug"), table_name="raffles")
    op.drop_index(op.f("ix_raffles_id"), table_name="raffles")
    op.drop_table("raffles")
    op.drop_index(op.f("ix_quotes_id"), table_name="quotes")
    op.drop_table("quotes")
    # ### end Alembic commands ###
